apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-pv-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/elasticsearch-0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/elasticsearch-1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-pv-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/elasticsearch-2
